export default {
  send: {
    disclaimers: 'Términos y condiciones',
    prompt1: 'Arrastre, pegue el texto, archivos aquí, o ',
    prompt2: 'Días<7 o límite de veces (elimina después de 24h)',
    prompt3: 'Ingrese el texto que desea enviar, admite formato MarkDown',
    share: 'Compartir',
    textShare: 'Compartir texto',
    clickUpload: 'Hacer clic para subir',
    pleaseInputExpireValue: 'Ingrese el período de validez',
    expireStyle: 'Método de caducidad',
    expireData: {
      day: 'Días',
      hour: 'Horas',
      forever: 'Para siempre',
      minute: 'Minutos',
      count: 'Veces'
    },
    expireValue: {
      day: 'Días',
      hour: 'Horas',
      minute: 'Minutos',
      count: 'Veces'
    },
    fileType: {
      file: 'Archivo',
      text: 'Texto'
    }
  },
  fileBox: {
    copySuccess: 'Copiado exitosamente',
    inputNotEmpty: 'Ingrese un código de recogida de cinco dígitos',
    sendFileBox: 'Buzón de envíos',
    ok: 'Aceptar',
    receiveFileBox: 'Buzón de recepción',
    textDetail: 'Detalles del texto',
    copy: 'Copiar',
    close: 'Cerrar',
    delete: 'Eliminar',
    download: 'Hacer clic para descargar',
    detail: 'Ver detalles',
    copyLink: 'Copiar enlace',
  },
  admin: {
    about: {
      source1: 'Proyecto de código abierto en Github:',
      source2: 'FileCodeBox'
    },
    settings: {
      name: 'Nombre del sitio web',
      description: 'Descripción del sitio web',
      uploadlimit: 'Límite de subida',
      explain: 'Descripción de la interfaz',
      errorlimit: 'Límite de errores',
      keywords: 'Palabras clave',
      notify_title: 'Título de notificación',
      notify_content: 'Contenido de notificación',
      background: 'Imagen de fondo',
      max_save_seconds: 'Tiempo máximo de almacenamiento',
      maxSaveSecondsNote: 'Tiempo máximo de almacenamiento, en segundos. El valor predeterminado es 0, que equivale a 7 días',
      admin_token: 'Contraseña de administración',
      uploadSize: 'Tamaño de archivo',
      expireStyle: 'Método de caducidad',
      uploadSizeNote: 'Tamaño máximo de archivo, en bytes. 1mb=1 * 1024 * 1024',
      openUpload: {
        title: 'Habilitar subida',
        open: 'Habilitar subida para visitantes',
        close: 'Deshabilitar subida para visitantes',
        note: 'Después de deshabilitar, es necesario iniciar sesión en el backend para poder subir archivos',
      },
      showAdmin: {
        open: 'abierto',
        close: 'cierre',
        note: 'si mostrar la entrada de fondo en la parte inferior de la página',
      },
      file_storage: {
        title: 'Motor de almacenamiento',
        local: 'Almacenamiento local',
        s3: 'Almacenamiento S3',
        note: 'Es necesario reiniciar FileCodeBox después de actualizar',
      },
      mei: 'Cada',
      minute: 'Minuto',
      upload: 'Subir',
      files: 'Archivos',
      allow: 'Permitir',
      errors: 'Errores',
      save: 'Guardar',
      saveSuccess: 'Guardado exitosamente',
    },
    fileView: {
      code: 'Código de recogida',
      prefix: 'Prefijo de archivo',
      suffix: 'Sufijo de archivo',
      text: 'Texto',
      used_count: 'Número de veces utilizado',
      expired_count: 'Número de veces disponible',
      size: 'Tamaño de archivo',
      expired_at: 'Fecha de caducidad',
      file_path: 'Ruta del archivo',
      action: 'Acción',
      delete: 'Eliminar',
      delete_success: 'Eliminado exitosamente',
      forever: 'Válido para siempre',
      unlimited_count: 'Número de veces ilimitado',
      download: 'Descargar',
      download_fail: 'Error al guardar el archivo, intente nuevamente más tarde~',
    },
    menu: {
      fileManage: 'Gestión de archivos',
      systemSetting: 'Configuración del sistema',
      about: 'Sobre nosotros',
      color: 'Modo de color',
      send: 'Enviar',
      receive: 'Recibir',
      signout: 'Cerrar sesión',
    },
    login: {
      managePassword: 'Contraseña de administración',
      passwordNotEmpty: 'La contraseña no puede estar vacía',
      login: 'Iniciar sesión',
      loginSuccess: 'Inicio de sesión exitoso',
      loginError: 'Error de inicio de sesión',
    }
  },
  msg: {
    fileOverSize: 'Archivo demasiado grande',
    fileUploadFail: 'Error al subir',
    fileUploadSuccess: 'Subida exitosa',
    uploadClose: 'El sitio ha deshabilitado la subida para visitantes',
  }
};