/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardTools: typeof import('./src/components/CardTools.vue')['default']
    FileBox: typeof import('./src/components/FileBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadFile: typeof import('./src/components/UploadFile.vue')['default']
    UploadText: typeof import('./src/components/UploadText.vue')['default']
  }
}
