"""init

Revision ID: 5a7ea072b184
Revises: 
Create Date: 2022-12-13 20:21:25.645856

"""
from alembic import op
import sqlalchemy as sa

import settings

# revision identifiers, used by Alembic.
revision = '5a7ea072b184'
down_revision = None
branch_labels = None
depends_on = None

engine = sa.create_engine(f"sqlite:///{settings.DATABASE_FILE}")

def upgrade() -> None:
    if sa.inspect(engine).has_table("codes"):
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('key', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('use_time', sa.DateTime(), nullable=True),
    sa.Column('exp_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codes_code'), 'codes', ['code'], unique=True)
    op.create_index(op.f('ix_codes_id'), 'codes', ['id'], unique=False)
    op.create_index(op.f('ix_codes_key'), 'codes', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_codes_key'), table_name='codes')
    op.drop_index(op.f('ix_codes_id'), table_name='codes')
    op.drop_index(op.f('ix_codes_code'), table_name='codes')
    op.drop_table('codes')
    # ### end Alembic commands ###
